version: '3.9'

services:
  n8n:
    privileged: true
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Manila
      - TZ=Asia/Manila
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_LICENSE=
    volumes:
      - ./devops/volumes/n8n_data:/home/node/.n8n

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    # command: tunnel --no-autoupdate run --token eyJhIjoiYzRlN2U5ODFhZTQwNDFlZmUwMTk5OWYxNDdjMGMwNjQiLCJ0IjoiNzQwYTYyNTktYmExYS00MDZmLThmNzEtNTkzZTY0ZmVkMWZjIiwicyI6Ik9ESXdZek5sWTJVdFkyWTJaQzAwT1RWbUxUZ3pPREF0Tm1Sa05qSTNaalEyT1RNeSJ9
    command: tunnel --url http://n8n:5678
    depends_on:
      - n8n

volumes:
  n8n_data: